import Head from 'next/head'
import React from 'react'
import Sidebar from '../Sidebar/Sidebar'

import styles from './Layout.module.css'

interface Props {
    children: React.ReactNode;
}

const Layout = ({ children }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Entertainment App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Sidebar />
      <main className={styles.main}>
        {children}
      </main>
    </div>
  )
}

export default Layout